	-- Delete any rows in case they already exist
    DELETE FROM path;
    DELETE FROM enzyme;
    DELETE FROM path_enzyme;

	-- Insert the pathways
	INSERT INTO path (id, name, class) VALUES ('hsa00232', 'Caffeine metabolism', 'Metabolism; Biosynthesis of other secondary metabolites');
	INSERT INTO path (id, name, class) VALUES ('hsa00983', 'Drug metabolism - other enzymes', 'Metabolism; Xenobiotics biodegradation and metabolism');

	
	-- Insert the enzymes
	INSERT INTO enzyme (id, sequence) VALUES ('P05177','MALSQSVPFSATELLLASAIFCLVFWVLKGLRPRVPKGLKSPPEPWGWPLLGHVLTLGKNPHLALSRMSQRYGDVLQIRIGSTPVLVLSRLDTIRQALVRQGDDFKGRPDLYTSTLITDGQSLTFSTDSGPVWAARRRLAQNALNTFSIASDPASSSSCYLEEHVSKEAKALISRLQELMAGPGHFDPYNQVVVSVANVIGAMCF');
	INSERT INTO enzyme (id, sequence) VALUES ('P18440','MDIEAYLERIGYKKSRNKLDLETLTDILQHQIRAVPFENLNIHCGDAMDLGLEAIFDQVVRRNRGGWCLQVNHLLYWALTTIGFETTMLGGYVYSTPAKKYSTGMIHLLLQVTIDGRNYIVDAGFGRSYQMWQPLELISGKDQPQVPCVFRLTEENGFWYLDQIRREQYIPNEEFLHSDLLEDSKYRKIYSFTLKPRTIEDFESMNT');
	INSERT INTO enzyme (id, sequence) VALUES ('P00492','MATRSPGVVISDDEPGYDLDLFCIPNHYAEDLERVFIPHGLIMDRTERLARDVMKEMGGHHIVALCVLKGGYKFFADLLDYIKALNRNSDRSIPMTVDFIRLKSYCNDQSTGDIKVIGGDDLSTLTGKNVLIVEDIIDTGKTMQTLLSLVRQYNPKMVKVASLLVKRTPRSVGYKPDFVGFEIPDKFVVGYALDYNEYFRDLNHVC');

	-- Associate the enzymes with the pathways
	INSERT INTO path_enzyme (path_id, enzyme_id) VALUES ('hsa00232','P05177');
	INSERT INTO path_enzyme (path_id, enzyme_id) VALUES ('hsa00232','P18440');
	INSERT INTO path_enzyme (path_id, enzyme_id) VALUES ('hsa00983','P00492');
	INSERT INTO path_enzyme (path_id, enzyme_id) VALUES ('hsa00983','P18440');